### PR TITLE
libsbp submodule update.

### PR DESCRIPTION
**Pull request by mookerji**
Updates the sbp integration tutorial to point to consume the libsbp
libraries as a submodule.

/cc @cbeighley @fnoble

### CODE REVIEW

**Comment by cbeighley** [comment]
Should I pull and try to build this?

**Comment by cbeighley** [comment]
Also, http://docs.swift-nav.com/wiki/Piksi_Integration_Tutorial needs updated references to libsbp documentation.

**Comment by mookerji** [comment]
ack, crap. I just realized that libswiftnav's not even needed for this project anymore.

**Comment by mookerji** [comment]
one second

**Comment by cbeighley** [comment]
Ran this on my Window install, just need to change:

```
  sbp_register_callback(&sbp_state, SBP_GPS_TIME, &sbp_gps_time_callback,
                        NULL, &gps_time_node);
  sbp_register_callback(&sbp_state, SBP_POS_LLH, &sbp_pos_llh_callback,
                        NULL, &pos_llh_node);
  sbp_register_callback(&sbp_state, SBP_BASELINE_NED, &sbp_baseline_ned_callback,
                        NULL, &baseline_ned_node);
  sbp_register_callback(&sbp_state, SBP_VEL_NED, &sbp_vel_ned_callback,
                        NULL, &vel_ned_node);
  sbp_register_callback(&sbp_state, SBP_DOPS, &sbp_dops_callback,
                        NULL, &dops_node);
```

to

```
  sbp_register_callback(&sbp_state, SBP_MSG_GPS_TIME, &sbp_gps_time_callback,
                        NULL, &gps_time_node);
  sbp_register_callback(&sbp_state, SBP_MSG_POS_LLH, &sbp_pos_llh_callback,
                        NULL, &pos_llh_node);
  sbp_register_callback(&sbp_state, SBP_MSG_BASELINE_NED, &sbp_baseline_ned_callback,
                        NULL, &baseline_ned_node);
  sbp_register_callback(&sbp_state, SBP_MSG_VEL_NED, &sbp_vel_ned_callback,
                        NULL, &vel_ned_node);
  sbp_register_callback(&sbp_state, SBP_MSG_DOPS, &sbp_dops_callback,
                        NULL, &dops_node);
```

Then good to merge.

**Comment by cbeighley** [comment]
Closes swift-nav/libsbp#27

**Comment by cbeighley** [comment]
I've also updated http://docs.swiftnav.com/wiki/Piksi_Integration_Tutorial

**Pull request merged**
